In [1]:
import pandas as pd
import protfasta
import itertools

In [2]:
# import sys
# sys.path.append('/global/home/users/sanjanakotha/labtools/')

import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
from labtools.adtools.sort import Sort
from labtools.adtools.counter import seq_counter
from labtools.adtools.finder import pull_AD
from labtools.adtools.seqlib import get_numreads
from labtools.adtools.counter import create_map, convert_bcs_from_map
from labtools.adtools.seqlib import write_bc_dict
from matplotlib import lines as mlines
import matplotlib
import numpy as np
from Bio.Seq import Seq

In [3]:
datanames_gfp8 = ["MYS3_001_S1_R1_001.fastq",
                 "MYS3_002_S2_R1_001.fastq",
                 'MYS3_003_S3_R1_001.fastq',
                 'MYS3_004_S4_R1_001.fastq',
                 'MYS3_005_S5_R1_001.fastq',
                 'MYS3_006_S6_R1_001.fastq',
                 'MYS3_007_S7_R1_001.fastq',
                 'MYS3_008_S8_R1_001.fastq']

# 1. Generating test seq

In [18]:
folder_path = '/global/scratch/projects/fc_mvslab/data/sequencing/CZB_Jan2024/MYS3/feb7/'
folder_path

'/global/scratch/projects/fc_mvslab/data/sequencing/CZB_Jan2024/MYS3/feb7/'

In [19]:
# Specify the path to your FASTQ file

for file in datanames_gfp8:
    fpath = folder_path + file
    with open(fpath, 'r') as f:
        beginning_lines = list(itertools.islice(f, 4*10000))
    
    pd.DataFrame([b.strip() for b in beginning_lines]).to_csv("../data/test_fastqs/test_" + file, index = None, header = None)

# 2. TESTING

In [4]:
mys3path = "../data/test_fastqs/test_"
mapfpath_all = '../output/sog1_lib1+2map_EC20250403.csv'#whenever we can save the bothlibsmap_fil to csv

In [5]:
datafiles_gfp8 = []
for f in datanames_gfp8:
    fpath = mys3path + f
    datafiles_gfp8.append(fpath)

In [16]:
# print(datafiles_gfp8)
bin_counts = [100,100,100,100,100,100,100,100]
bin_values_gfp8 = [146,237,331,483,776,1364,2592,6357]
gfp8wayfiles = Sort(datafiles_gfp8, bin_counts, bin_values_gfp8, bc_dict = True)

In [17]:
gfp1_activity, gfp1_reads, gfp1_bins, gfp1_loss_table = gfp8wayfiles.process(ad_preceder = "GCTAGC",
                                   bc_preceder = "GGGCCCG",
                                   bc_anteceder = "GGCGCGCC", 
                                   ad_length = 120,
                                   bclength = 11)

Opening file test_MYS3_001_S1_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_002_S2_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_003_S3_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_004_S4_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_005_S5_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_006_S6_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_007_S7_R1_001.fastq ...
Total parsed reads = 10,000
Opening file test_MYS3_008_S8_R1_001.fastq ...
Total parsed reads = 10,000

In [19]:
gfp1_activity

,0,1,2,3,4,5,6,7,Activity
ACCGGCTACCC,0.261601,0.304337,0.221326,0.142607,0.045282,0.014846,0.010002,0.000000,333.772963
CCGCGTGCCCA,0.159906,0.458427,0.144726,0.095471,0.141469,0.000000,0.000000,0.000000,335.790694
GTCACCAGTGG,0.288594,0.263250,0.237452,0.164472,0.034816,0.011415,0.000000,0.000000,305.149347
TGTCCGCTGGC,0.333830,0.343554,0.139449,0.137986,0.022718,0.011173,0.011291,0.000000,305.100772
AAGGGACTCGC,0.110263,0.135476,0.270875,0.268033,0.160261,0.047975,0.000000,0.007117,502.370129
...,...,...,...,...,...,...,...,...,...
CCAATGGAAAA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.075010,0.924990,6074.588532
GGGCCGGTATT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
CTAGGTTGCAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
TCAATTGTTGC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
TTGGAGCCACA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000

In [20]:
len(gfp1_activity.index[0])

11

In [21]:
len(set(gfp1_activity.index))

1438

In [22]:
bc_dict = pd.read_csv(mapfpath_all)
bc_dict

,AAAAAAAAAAA,AAAAAAAAAAC,AAAAAAAAAAG,AAAAAAAAACA,AAAAAAAAACC,AAAAAAAAACG,AAAAAAAAACT,AAAAAAAAAGG,AAAAAAAAAGT,AAAAAAAAATA,...,TTTTTTTGATC,TTTTTTTGATT,TTTTTTTGCTA,TTTTTTTGCTG,TTTTTTTGTCC,TTTTTTTGTGC,TTTTTTTTGAT,TTTTTTTTGGC,TTTTTTTTTCG,TTTTTTTTTTT
0,GCTTTGTGTGATGAGTTCTTGTTGGCTCAAGCTCAAACTTCTTGTG...,CAGAAGATTGTCTTGGATCCATCTAATATTGAAGCTGATACTCCAC...,TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGATGCTA...,GGTTCTCAAGCTAGAGAAGAGAATACTAATTCTGGTTCTTTGAAAG...,GCTGAATTTATTCCAACTGTTAATCAAGATGCTGGTATTTGTTATA...,AGGAAGATGGAAGTCTTGGCTGTTGATGATGAAGATTGTGAACCAT...,GGTGTTGCTGGTGATGAAGAAGCATTTGATGATTTGAAGATGTTTG...,CAGAAGATTGTCTTGAATCCATCTAATATTCAAGCTAATACTCCAC...,CAGAAGATTGTCTTGGATCCATCTAATATTGAATTGGATGCTCCAC...,CCAGGTATGGAGAATCATGTTGATCAAATGGTTGGTGATAATGATA...,...,GAAGATCCAGCTTGGTTTGATGATGATGCTGACTTTGATTTGGATG...,CAGAAGATTGTCTTGGATCCAGAAGAAATTGAATTGGATGAAGAAC...,GCTACTCCAACTGTTGCTGCATTTATTGATGATCCAGTTACTCCTA...,AAGAAATTGAGAGTTAATGCTATTGGTGTTGTTGATGTTTATAAAG...,CCACAGAACTTTAGGAAATACTTTACTGCATTTAATTCTAACTTTG...,AGATTGGCTAGAGTCTTGTTCTTGCATTTGTATTTGTTCTTGACTA...,CAACAACCACAACAATTGGTTGTTGGTGGTGGTGGTGGTGCTGGTC...,GTTGCTATGGCTCATGCTGATGCTTTGGATGACTTTGATTTGGATA...,CAATATAAAGAAGGTCAGAATGGTGGTGGTACTAGATCTCAATTCT...,GACTTTAAGAGAGATTTGGAAGAGAATATTGTTTGTTTGCAATCTG...

In [23]:
bc_dict = bc_dict.T
bc_dict

                                                             0
AAAAAAAAAAA  GCTTTGTGTGATGAGTTCTTGTTGGCTCAAGCTCAAACTTCTTGTG...
AAAAAAAAAAC  CAGAAGATTGTCTTGGATCCATCTAATATTGAAGCTGATACTCCAC...
AAAAAAAAAAG  TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGATGCTA...
AAAAAAAAACA  GGTTCTCAAGCTAGAGAAGAGAATACTAATTCTGGTTCTTTGAAAG...
AAAAAAAAACC  GCTGAATTTATTCCAACTGTTAATCAAGATGCTGGTATTTGTTATA...
...                                                        ...
TTTTTTTGTGC  AGATTGGCTAGAGTCTTGTTCTTGCATTTGTATTTGTTCTTGACTA...
TTTTTTTTGAT  CAACAACCACAACAATTGGTTGTTGGTGGTGGTGGTGGTGCTGGTC...
TTTTTTTTGGC  GTTGCTATGGCTCATGCTGATGCTTTGGATGACTTTGATTTGGATA...
TTTTTTTTTCG  CAATATAAAGAAGGTCAGAATGGTGGTGGTACTAGATCTCAATTCT...
TTTTTTTTTTT  GACTTTAAGAGAGATTTGGAAGAGAATATTGTTTGTTTGCAATCTG...

[623670 rows x 1 columns]

In [24]:
bc_dict

                                                             0
AAAAAAAAAAA  GCTTTGTGTGATGAGTTCTTGTTGGCTCAAGCTCAAACTTCTTGTG...
AAAAAAAAAAC  CAGAAGATTGTCTTGGATCCATCTAATATTGAAGCTGATACTCCAC...
AAAAAAAAAAG  TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGATGCTA...
AAAAAAAAACA  GGTTCTCAAGCTAGAGAAGAGAATACTAATTCTGGTTCTTTGAAAG...
AAAAAAAAACC  GCTGAATTTATTCCAACTGTTAATCAAGATGCTGGTATTTGTTATA...
...                                                        ...
TTTTTTTGTGC  AGATTGGCTAGAGTCTTGTTCTTGCATTTGTATTTGTTCTTGACTA...
TTTTTTTTGAT  CAACAACCACAACAATTGGTTGTTGGTGGTGGTGGTGGTGCTGGTC...
TTTTTTTTGGC  GTTGCTATGGCTCATGCTGATGCTTTGGATGACTTTGATTTGGATA...
TTTTTTTTTCG  CAATATAAAGAAGGTCAGAATGGTGGTGGTACTAGATCTCAATTCT...
TTTTTTTTTTT  GACTTTAAGAGAGATTTGGAAGAGAATATTGTTTGTTTGCAATCTG...

[623670 rows x 1 columns]

In [25]:
gfp1_activity_with_AD = pd.merge(gfp1_activity, bc_dict, left_index= True, right_index = True, how = 'left').dropna()
gfp1_activity_with_AD

,0_x,1,2,3,4,5,6,7,Activity,0_y
TGTCCGCTGGC,0.333830,0.343554,0.139449,0.137986,0.022718,0.011173,0.011291,0.000000,305.100772,GATATCTTTGCTGCTGTTGCTCCAGCTGCTGATCCAGATGATCCTA...
TTGTCCCTAAG,0.396196,0.265029,0.161363,0.177411,0.000000,0.000000,0.000000,0.000000,259.757446,GAAGGTAATTCTTCTAAAGCTGAAACTTGTCAACCACAACCAAGAT...
CCCAGGCCTTA,0.256457,0.398248,0.116056,0.143548,0.056722,0.000000,0.000000,0.028969,467.747998,TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGCTGCTA...
GGACAAGGTAA,0.347135,0.165864,0.216000,0.213733,0.038389,0.018879,0.000000,0.000000,320.261686,CAACAACCACAACAATTGGTTGTTAAGAGAGGTGATAAAGCTGAAC...
ACCTCCAAACG,0.238993,0.437740,0.252356,0.035673,0.035240,0.000000,0.000000,0.000000,266.742684,GAAATGTTGGATGATAAAGAAGAACAAGAGAAAGATAGAGATAATG...
...,...,...,...,...,...,...,...,...,...,...
GTCCTGAGCCA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.088681,0.911319,6023.115157,ATTTATAATGAAGCTCCAGAATTTGATGGTTATGATGTTTCTCCAA...
CCAATGGAAAA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.075010,0.924990,6074.588532,AAAGATAGAGATAATGAGAATCAAGGTGAAGAAGATCCAACTTGGT...
GGGCCGGTATT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,CATAATTCTCCAGAAGCTCCAATCTTGTTTCCAGATGATTGGTATC...
CTAGGTTGCAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,TTGTGGGAAGGTGATTCTCAATTTGAATTGTTGGATTCTCAACAAT...
TCAATTGTTGC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,TTGTGGGAAGGTGATGATCAATTTGAATTGTTGGATGATCAACAAT...

In [26]:
len(gfp1_activity_with_AD["0_y"].unique())

774

In [27]:
# Seems to be working!

# 3. Repeat with all sequences

In [29]:
mys3path = '/global/scratch/projects/fc_mvslab/data/sequencing/CZB_Jan2024/MYS3/feb7/'
# gdnamappath = '/global/scratch/projects/fc_mvslab/data/sequencing/CZB_Feb2024/Sog1_Lib2_map/map_outputs/'
mapfpath_lib2 = '/global/scratch/projects/fc_mvslab/OpenProjects/EChase/sog1/EC_analysis/sog1_lib2_barcode_map_EC.csv'
mapfpath_all = '../output/sog1_lib1+2map_EC20250403.csv'#whenever we can save the bothlibsmap_fil to csv

# USE READ 1 NOT ASSEMBLED

datanames_gfp8 = ["MYS3_001_S1_R1_001.fastq",
                 "MYS3_002_S2_R1_001.fastq",
                 'MYS3_003_S3_R1_001.fastq',
                 'MYS3_004_S4_R1_001.fastq',
                 'MYS3_005_S5_R1_001.fastq',
                 'MYS3_006_S6_R1_001.fastq',
                 'MYS3_007_S7_R1_001.fastq',
                 'MYS3_008_S8_R1_001.fastq']
datafiles_gfp8 = []
for f in datanames_gfp8:
    fpath = mys3path + f
    datafiles_gfp8.append(fpath)

# print(datafiles_gfp8)
bin_counts = [100,100,100,100,100,100,100,100]
bin_values_gfp8 = [146,237,331,483,776,1364,2592,6357]
gfp8wayfiles = Sort(datafiles_gfp8, bin_counts, bin_values_gfp8, bc_dict = True)

gfp1_activity, gfp1_reads, gfp1_bins, gfp1_loss_table =  gfp8wayfiles.process(ad_preceder = "GCTAGC",
                                   bc_preceder = "GGGCCCG",
                                   bc_anteceder = "GGCGCGCC", 
                                   ad_length = 120,
                                   bclength = 11)

Opening file MYS3_001_S1_R1_001.fastq ...
Total parsed reads = 119,788,454
Opening file MYS3_002_S2_R1_001.fastq ...
Total parsed reads = 116,842,528
Opening file MYS3_003_S3_R1_001.fastq ...
Total parsed reads = 135,400,512
Opening file MYS3_004_S4_R1_001.fastq ...
Total parsed reads = 139,455,679
Opening file MYS3_005_S5_R1_001.fastq ...
Total parsed reads = 121,908,963
Opening file MYS3_006_S6_R1_001.fastq ...
Total parsed reads = 150,376,570
Opening file MYS3_007_S7_R1_001.fastq ...
Total parsed reads = 140,260,726
Opening file MYS3_008_S8_R1_001.fastq ...
Total parsed reads = 128,817,384

In [30]:
gfp1_activity

,0,1,2,3,4,5,6,7,Activity
CCCAGATGAGC,0.118104,0.223959,0.215195,0.143027,0.199025,0.080679,0.018177,0.001832,533.886922
TACCGATCAAA,0.503649,0.187121,0.199831,0.000491,0.108419,0.000000,0.000489,0.000000,269.661041
TCCGTCTCCTG,0.587587,0.222934,0.040448,0.134129,0.000000,0.014902,0.000000,0.000000,237.122104
ACCGGCTACCC,0.258554,0.274362,0.219599,0.161592,0.046051,0.021799,0.009501,0.008541,397.902412
TCTGTTGTAAC,0.413736,0.375313,0.120563,0.081555,0.005883,0.002695,0.000110,0.000144,238.096241
...,...,...,...,...,...,...,...,...,...
AGTCCTCGTAG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
TCCAGAGAGAA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
CGGCGGTGTGC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
ACGGCCATAGT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000
ATAGGTGTGCA,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000

In [31]:
bc_dict

                                                             0
AAAAAAAAAAA  GCTTTGTGTGATGAGTTCTTGTTGGCTCAAGCTCAAACTTCTTGTG...
AAAAAAAAAAC  CAGAAGATTGTCTTGGATCCATCTAATATTGAAGCTGATACTCCAC...
AAAAAAAAAAG  TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGATGCTA...
AAAAAAAAACA  GGTTCTCAAGCTAGAGAAGAGAATACTAATTCTGGTTCTTTGAAAG...
AAAAAAAAACC  GCTGAATTTATTCCAACTGTTAATCAAGATGCTGGTATTTGTTATA...
...                                                        ...
TTTTTTTGTGC  AGATTGGCTAGAGTCTTGTTCTTGCATTTGTATTTGTTCTTGACTA...
TTTTTTTTGAT  CAACAACCACAACAATTGGTTGTTGGTGGTGGTGGTGGTGCTGGTC...
TTTTTTTTGGC  GTTGCTATGGCTCATGCTGATGCTTTGGATGACTTTGATTTGGATA...
TTTTTTTTTCG  CAATATAAAGAAGGTCAGAATGGTGGTGGTACTAGATCTCAATTCT...
TTTTTTTTTTT  GACTTTAAGAGAGATTTGGAAGAGAATATTGTTTGTTTGCAATCTG...

[623670 rows x 1 columns]

In [32]:
gfp1_activity_with_AD = pd.merge(gfp1_activity, bc_dict, left_index= True, right_index = True, how = 'left').dropna()
gfp1_activity_with_AD

,0_x,1,2,3,4,5,6,7,Activity,0_y
TCCGTCTCCTG,0.587587,0.222934,0.040448,0.134129,0.000000,0.014902,0.000000,0.000000,237.122104,CAAGCTTTGTCTTTGTGTAATAATTTGTTGGGTTCTCAGAATAGAC...
TCTGTTGTAAC,0.413736,0.375313,0.120563,0.081555,0.005883,0.002695,0.000110,0.000144,238.096241,TTGGAACATGGTTTGGAGAATGGTGCTGCTGCTGCTTTGGATGATA...
TAGTTCGCCCT,0.268681,0.313838,0.252722,0.035037,0.082433,0.047289,0.000000,0.000000,342.651124,ACTTGGGAACCAGACTTTGATTCTGGTTCTCAATTTATCTTAAATT...
TGTCCGCTGGC,0.314635,0.307595,0.198097,0.128112,0.024464,0.015612,0.006488,0.004998,335.152026,GATATCTTTGCTGCTGTTGCTCCAGCTGCTGATCCAGATGATCCTA...
GGCTTCGTGAA,0.486986,0.377752,0.097760,0.021031,0.003402,0.004643,0.005513,0.002912,244.920500,TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGCTGCTA...
...,...,...,...,...,...,...,...,...,...,...
CCCGAGAGCAC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,TTGGCTCATGGTTTGGCTAATGGTGCTAAAGCTATGTTGGCTGCTA...
CCTTACGAGGT,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,AAAGATAGAGATCAAGAGAATGAAGGTAATGAAGATCCAACTTGGT...
ATGCAGAAATC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,GGTGATAAAGCTGAACAAGAAGTTTCTGAAGATATCTTTGCTGCTG...
CTCAAATGACG,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,GCTAATGTTAATGAATTTGGTTTGGTTAATCATCAAGCTCATCAAA...
TGCCCGACACC,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,6357.000000,CAAGCTATCTTAAATTCTCAACAAGCTGTTGAAGCTTTGTCTTTGT...

In [33]:
len(set(gfp1_activity_with_AD["0_y"]))

11387

In [34]:
gfp1_activity_with_AD.to_csv("../output/testgfp1_activity_SK_by_barcode.csv")

In [37]:
gfp1_bins.to_csv("../output/testgfp1_bins_SK_by_barcode.csv")

In [39]:
gfp1_bins

,0,1,2,3,4,5,6,7
CCCAGATGAGC,11794.0,21846.0,24339.0,16657.0,20272.0,10129.0,2129.0,197.0
TACCGATCAAA,879.0,319.0,395.0,1.0,193.0,0.0,1.0,0.0
TCCGTCTCCTG,4579.0,1697.0,357.0,1219.0,0.0,146.0,0.0,0.0
ACCGGCTACCC,561170.0,581667.0,539819.0,409021.0,101947.0,59483.0,24187.0,19958.0
TCTGTTGTAAC,15995.0,14173.0,5279.0,3677.0,232.0,131.0,5.0,6.0
...,...,...,...,...,...,...,...,...
AGTCCTCGTAG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0
TCCAGAGAGAA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
CGGCGGTGTGC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
ACGGCCATAGT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0
ATAGGTGTGCA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0

In [38]:
pd.DataFrame(gfp1_reads)

                     0
CCCAGATGAGC   107363.0
TACCGATCAAA     1788.0
TCCGTCTCCTG     7998.0
ACCGGCTACCC  2297252.0
TCTGTTGTAAC    39498.0
...                ...
AGTCCTCGTAG       12.0
TCCAGAGAGAA       11.0
CGGCGGTGTGC       11.0
ACGGCCATAGT       11.0
ATAGGTGTGCA       15.0

[199576 rows x 1 columns]

In [ ]:
gfp1_activity_with_AD.to_csv("../output/testgfp1_activity_SK_by_barcode.csv")

In [19]:
len(set(gfp1_activity.index))

73

In [12]:
gfp1_reads

AD
AAAGATAGAGATAATGAGAATCAAGGTGAAGAAGATCCAACTTGGGCTGATTCTGGTTCTCAATTTATCTTAAATTCTCAACAATTGGTTGAAGCTTTGTCTTTGTGTGATGATGCTTTG    18.0
AAATGTCAACATGTTATTGATAATTCTGATGTTGTTGATGATTGGCCAGGTTTGCCAAGAGGTGTTAAATTTGATCCATCTGCTCCAGCTATTATTTGGCATTTGTTGGCTAAATCTGGT    11.0
ACTGGTTTGTCTCAAGATGATGACTTTGTTCCATGGTTGAATCATCATCCATCTTTGGATGGTTATTGTTCTGACTTCTTGAGAGATGTTTCTTCTCCAGTTACTGTTAATGAACAAGAA    14.0
ATTATTGCTCATTTGTTGGCTAAATCTGGTGCTTCTGGTTTGTCTTCTCATCCATTTATTGATGAATTTATTCCAACTGTTAATCAAGATGATGGTATTTGTTATACTCATCCTAAGAAT    11.0
ATTGAATTGGATACTCCACCAGACTTTAGATTGTCTCAATTGGAATTTGAATCTCAAGATTCTTATACTCCATGGGTTGGTACTAAAGTTGGTGCTGAATGGTCTATGGGTGCTAATTTG    13.0
                                                                                                                            ...
GAAGATCCAGCTTGGTTTGATGCTGGTGCTCAATTTGAATTGGAAGCTCAACAATTGGAAGAAGCTTTGTCTTTGTGTGATGATTTGTTGGGTGCTCAAGATAGAGAAGAGAATGCTAAT    19.0
ATTGATGCTGCTCCATTCTTGAATGAATCATTTGAAACTGCTCCAATGTTTCAAGGTGAACCATTGATGAATAATTCTAATGATTGGTTCTCTTTGTTTCCAGAAGAAGAGAATAAATTG    16.0
GAAATGTTGGATGATAAAGAAGAACAAGAGAAAGATAGAGATAATGAGAATCAAGGTGAATCTGATGGATTTGAATCTCCAACTGATTGGCAATTTATCTTAAATTCTCAACAATTGGTT    28.0
GAAGATCCAACTTGGTTTGATTCTGATGCTCAATTTGATTTGGATGCTCAAGATTTGGATGAAGCTTTGTCTTTGTGTGATGATTTGTTGGGTGCTCAAGATAGAGAAGAGAATACTAAT    12.0
GATCAATTTGAATTGTTGGATGATCAACAATTGGCTGAAGGTTTGGCTTTGTGTGATGAGTTCTTGTTGGATCAAGATCAAACTTCTTGTGGTGGTGGTGATGAACCAAGAGAAACTAAA    27.0
Length: 73, dtype: float64

In [13]:
gfp1_bins

,0,0,0,0,0,0,0,0
AD,,,,,,,,
AAAGATAGAGATAATGAGAATCAAGGTGAAGAAGATCCAACTTGGGCTGATTCTGGTTCTCAATTTATCTTAAATTCTCAACAATTGGTTGAAGCTTTGTCTTTGTGTGATGATGCTTTG,3.0,2.0,7.0,4.0,2.0,0.0,0.0,0.0
AAATGTCAACATGTTATTGATAATTCTGATGTTGTTGATGATTGGCCAGGTTTGCCAAGAGGTGTTAAATTTGATCCATCTGCTCCAGCTATTATTTGGCATTTGTTGGCTAAATCTGGT,2.0,5.0,1.0,1.0,2.0,0.0,0.0,0.0
ACTGGTTTGTCTCAAGATGATGACTTTGTTCCATGGTTGAATCATCATCCATCTTTGGATGGTTATTGTTCTGACTTCTTGAGAGATGTTTCTTCTCCAGTTACTGTTAATGAACAAGAA,1.0,0.0,1.0,0.0,0.0,3.0,6.0,3.0
ATTATTGCTCATTTGTTGGCTAAATCTGGTGCTTCTGGTTTGTCTTCTCATCCATTTATTGATGAATTTATTCCAACTGTTAATCAAGATGATGGTATTTGTTATACTCATCCTAAGAAT,3.0,3.0,2.0,1.0,0.0,1.0,1.0,0.0
ATTGAATTGGATACTCCACCAGACTTTAGATTGTCTCAATTGGAATTTGAATCTCAAGATTCTTATACTCCATGGGTTGGTACTAAAGTTGGTGCTGAATGGTCTATGGGTGCTAATTTG,1.0,0.0,2.0,0.0,0.0,7.0,3.0,0.0
...,...,...,...,...,...,...,...,...
GAAGATCCAGCTTGGTTTGATGCTGGTGCTCAATTTGAATTGGAAGCTCAACAATTGGAAGAAGCTTTGTCTTTGTGTGATGATTTGTTGGGTGCTCAAGATAGAGAAGAGAATGCTAAT,0.0,0.0,0.0,0.0,0.0,1.0,5.0,13.0
ATTGATGCTGCTCCATTCTTGAATGAATCATTTGAAACTGCTCCAATGTTTCAAGGTGAACCATTGATGAATAATTCTAATGATTGGTTCTCTTTGTTTCCAGAAGAAGAGAATAAATTG,0.0,0.0,0.0,0.0,0.0,0.0,4.0,12.0
GAAATGTTGGATGATAAAGAAGAACAAGAGAAAGATAGAGATAATGAGAATCAAGGTGAATCTGATGGATTTGAATCTCCAACTGATTGGCAATTTATCTTAAATTCTCAACAATTGGTT,0.0,0.0,0.0,0.0,0.0,0.0,5.0,23.0
GAAGATCCAACTTGGTTTGATTCTGATGCTCAATTTGATTTGGATGCTCAAGATTTGGATGAAGCTTTGTCTTTGTGTGATGATTTGTTGGGTGCTCAAGATAGAGAAGAGAATACTAAT,0.0,0.0,0.0,0.0,0.0,0.0,2.0,10.0
GATCAATTTGAATTGTTGGATGATCAACAATTGGCTGAAGGTTTGGCTTTGTGTGATGAGTTCTTGTTGGATCAAGATCAAACTTCTTGTGGTGGTGGTGATGAACCAAGAGAAACTAAA,0.0,0.0,0.0,0.0,0.0,0.0,11.0,16.0