In [2]:
import pandas as pd

In [3]:
sog1_aa_features = pd.read_excel("../margot_raw/SOG1_AAfeatures_Lib1+2.xlsx", header = 1)
sog1_aa_features = sog1_aa_features.rename(columns = {"Unnamed: 0" : "pos",
                                                      "Unnamed: 1" : "aa", 
                                                      "Unnamed: 2" : "part",
                                                      "Lib1" : "PS_lib1",
                                                      "Lib2": "PS_lib2",
                                                      "Lib1.1" : "charge_lib1",
                                                      "Lib2.1" : "charge_lib2",
                                                      "Lib1.2" : "hydrophob_lib1",
                                                      "Lib2.2" : "hydrophob_lib2"})
sog1_aa_features.to_csv("../data/Sog1_AA_features.csv")
sog1_aa_features

,pos,aa,part,PS_lib1,PS_lib2,charge_lib1,charge_lib2,hydrophob_lib1,hydrophob_lib2
0,1,M,NTD,NaN,NaN,NaN,NaN,NaN,NaN
1,2,A,NTD,NaN,NaN,NaN,NaN,NaN,NaN
2,3,G,NTD,NaN,NaN,NaN,NaN,NaN,NaN
3,4,R,NTD,NaN,NaN,NaN,positive,NaN,NaN
4,5,S,NTD,potential,potential,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
444,445,T,CTD,potential,potential,NaN,NaN,NaN,NaN
445,446,G,CTD,NaN,NaN,NaN,NaN,NaN,NaN
446,447,K,CTD,NaN,NaN,NaN,positive,NaN,NaN
447,448,T,CTD,potential,potential,NaN,NaN,NaN,NaN
448,449,D,CTD,NaN,NaN,negative,negative,NaN,NaN

In [4]:
library = pd.read_excel("../margot_raw/SeqLib_Visit2_2023.xlsx", sheet_name = "Visit2")
library

,No.,Library,Species,Protein,BasicSOG1,RegionSOG1,StartAA,StopAA,Size,Type,...,HFB_exact,HFB_extent,HEL,SHU_MJ,SHU_extent,SCAN_exact,SCAN_extent,Description,ProteinSeq,Other
0,NaN,2,SaCe,GAL4,NaN,NaN,NaN,NaN,40,CRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AD1_0,STIPLDFMPRDALHGFDWSEEDDMSDGLPFLKTDPNNNGF,GAL4_AD1_0
1,NaN,2,SaCe,GAL4,NaN,NaN,NaN,NaN,40,CRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AD1_Aro2A_0,STIPLDAMPRDALHGADASEEDDMSDGLPALKTDPNNNGA,GAL4_AD1_Aro2A_0
2,NaN,2,SaCe,GAL4,NaN,NaN,NaN,NaN,40,CRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AD1_L2A_0,STIPADFMPRDAAHGFDWSEEDDMSDGAPFAKTDPNNNGF,GAL4_AD1_L2A_0
3,NaN,2,SaCe,GCN4,NaN,NaN,NaN,NaN,40,CRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAAD40_0,STDSTPMFEYENLEDNSKEWTSLFDNDIPVTTDDVSLADK,GCN4_CAAD40_0
4,NaN,2,SaCe,GCN4,NaN,NaN,NaN,NaN,40,CRL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,CAAD40_WLF_A_0,STDSTPMFEYENLEDNSKEATSAADNDIPVTTDDVSLADK,GCN4_CAAD40_WLF_A_0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23344,NaN,2,ArTh,SOG1,37,R3,361,400,40,PSvsCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37_PSvsCHA_hyperE_DD_all,EALSLCDDLDDEQDREENTNSGSLKDKQPCIADYAHLGPE,/
23345,NaN,2,ArTh,SOG1,38,R3,371,410,40,PSvsCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38_PSvsCHA_hyperE_DD_all,DEQDREEDTNSGSLKDKQPCIADYAHLGPEDFKRDLEECQ,/
23346,NaN,2,ArTh,SOG1,40,R4,391,430,40,PSvsCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40_PSvsCHA_hyperE_DD_all,IADYAHLGPEDFKRDLEECQKIVLDPSNDEDDEPPEDRDE,Pro subst
23347,NaN,2,ArTh,SOG1,41,R4,401,440,40,PSvsCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,41_PSvsCHA_hyperE_DD_all,DFKRDLEECQKIVLDPSNDEDDEPPEFRDEQDEFDEQDDF,Pro subst
23348,NaN,2,ArTh,SOG1,42,R4,410,449,40,PSvsCHA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42_PSvsCHA_hyperE_DD_all,QKIVLDPSNDEDDEPPEFRDEQDEFDEQDDFLAWGTGKTD,Pro subst

In [14]:
#library = library[["StartAA", "StopAA", "ProteinSeq", "Description", "Other"]]
library["Description"] = library["Description"].astype(str)
library = library.rename(columns = {"StartAA" : "Start", "StopAA" : "End"})
library

,Start,End,ProteinSeq,Description,Other
0,NaN,NaN,STIPLDFMPRDALHGFDWSEEDDMSDGLPFLKTDPNNNGF,AD1_0,GAL4_AD1_0
1,NaN,NaN,STIPLDAMPRDALHGADASEEDDMSDGLPALKTDPNNNGA,AD1_Aro2A_0,GAL4_AD1_Aro2A_0
2,NaN,NaN,STIPADFMPRDAAHGFDWSEEDDMSDGAPFAKTDPNNNGF,AD1_L2A_0,GAL4_AD1_L2A_0
3,NaN,NaN,STDSTPMFEYENLEDNSKEWTSLFDNDIPVTTDDVSLADK,CAAD40_0,GCN4_CAAD40_0
4,NaN,NaN,STDSTPMFEYENLEDNSKEATSAADNDIPVTTDDVSLADK,CAAD40_WLF_A_0,GCN4_CAAD40_WLF_A_0
...,...,...,...,...,...
23344,361,400,EALSLCDDLDDEQDREENTNSGSLKDKQPCIADYAHLGPE,37_PSvsCHA_hyperE_DD_all,/
23345,371,410,DEQDREEDTNSGSLKDKQPCIADYAHLGPEDFKRDLEECQ,38_PSvsCHA_hyperE_DD_all,/
23346,391,430,IADYAHLGPEDFKRDLEECQKIVLDPSNDEDDEPPEDRDE,40_PSvsCHA_hyperE_DD_all,Pro subst
23347,401,440,DFKRDLEECQKIVLDPSNDEDDEPPEFRDEQDEFDEQDDF,41_PSvsCHA_hyperE_DD_all,Pro subst
23348,410,449,QKIVLDPSNDEDDEPPEFRDEQDEFDEQDDFLAWGTGKTD,42_PSvsCHA_hyperE_DD_all,Pro subst

In [15]:
library.to_csv("../data/visit2_seq_lib.csv")